### ISSUE TITLE
"TH_INDEX_BASE" is undefined

### ISSUE THREAD

**Issue by KevinCain** [callmeray/PointMVSNet#1]
While I have no trouble in Ubuntu 18.04 installing dependencies, subsequent compilation yields this error:

> csrc/gather_knn_kernel.cu(84): error: identifier "TH_INDEX_BASE" is undefined

From [this thread](https://github.com/torch/cutorch/issues/480) I gather that the problem could be an update sequence, however after `conda update pytorch`, et cetera, I see the same error.

Any tips?

Note, I found I need to add the ‘.txt’ suffix for the dependencies file referenced in ‘ install_dependencies.sh’.

My steps:

```
git clone https://github.com/callmeray/PointMVSNet && cd PointMVSNet
bash install_dependencies.sh
source activate PointMVSNet (the Conda environment from the above script)
bash compile.sh
```

**Comment by callmeray** [comment]
Hi Kevin,
This problem is due to the new version of Pytorch. Could you downgrade your PyTorch to 1.0.0 or 1.0.1 and try it again?

**Comment by KevinCain** [comment]
Thanks for your fast, helpful reply!

As you suggested, I downgraded to PyTorch 1.0.0 and can get a bit further in compilation.  However, now I receive several errors that appear to relate to the c++/g++ version.

From your notes I believe you're running **gcc-5**, but in my build environment I see references to gcc6, as in the following error:

```
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/usr/include/c++/6/tuple:484:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^

```

I've tried gcc/G++ 5 and 6, as below, but see the same errors.

Am I missing something obvious?  I note the following warning:

> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

```
sudo apt-get update
sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++
sudo apt install g++-5
sudo apt install gcc-5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
```

For gcc/g++ 6:
```
sudo apt install g++-6
sudo apt install gcc-6
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
```

**Comment by callmeray** [comment]
I have not encountered such errors. I guess it's related to the driver version and CUDA version

**Comment by KevinCain** [comment]
It turns out I can now build without errors after reverting to CUDNN 7.4.2 for Ubuntu 18.04.  Thanks again @callmeray for your help.

**Comment by YunzeMan** [comment]
@KevinCain Hi, I wonder what CUDA version are you using? I.m also Ubuntu 18.04 with CUDA 9.2. Not sure if I should install 9.0 cuda.

**Comment by hychiang-git** [comment]
Not sure if I was right. I read this [website](https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide) and set `TH_INDEX_BASE=0.` works for me

**Comment by kwea123** [comment]
Yes, just replace `TH_INDEX_BASE` with `0` simply works. torch version doesn't matter. I'm using torch 1.4.0.

**Comment by alimurreza** [comment]
> Yes, just replace `TH_INDEX_BASE` with `0` simply works. torch version doesn't matter. I'm using torch 1.4.0.

I was getting the same error in the following line:
csrc/gather_knn_kernel.cu(84): error: identifier "TH_INDEX_BASE" is undefined

I replaced the TN_INDEX_BASE with 0 (inside the file "csrc/gather_knn_kernel.cu")and it compiled successfully.

Thanks,

**Comment by cuge1995** [comment]
> Not sure if I was right. I read this [website](https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide) and set `TH_INDEX_BASE=0.` works for me

Where TH_INDEX_BASE is ?

**Comment by cuge1995** [comment]
why still have bugs
```shell
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (5, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/include/c++/6/type_traits:1558:8: note: provided for ‘template<class _From, class _To> struct std::is_convertible’
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
```

**Comment by wangmiaowei** [comment]
How to  replace TH_INDEX_BASE with 0 ?
