### ISSUE TITLE
name 'dgcnn_ext' is not defined

### ISSUE THREAD

**Issue by XGBoost** [callmeray/PointMVSNet#14]
When I complete the compiling, it reminds me as following:
![image](https://user-images.githubusercontent.com/23393128/75160514-14bd2c00-5755-11ea-8470-8312e96775eb.png)
When I test if the corresponding function is built correctly, I check it by
![image](https://user-images.githubusercontent.com/23393128/75160587-3b7b6280-5755-11ea-9a06-d3bcc6d20d39.png)
I wonder how to solve the problem

**Comment by XGBoost** [comment]
When I try to import dgcnn, it reminds me that
![image](https://user-images.githubusercontent.com/23393128/75250061-7394ab00-5812-11ea-9090-e75d0914bb61.png)

undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by zhaozj19** [comment]
我也遇到了这个错误，您最后是怎么解决的？

**Comment by XGBoost** [comment]
@zhaozj19 
I install the same version package and environment as the author recommended. The above problem is solved.
I advise you to check you environment and package version.

**Comment by zhaozj19** [comment]
@XGBoost Do you use linux or windows? I am using win10, and useless GCC.

**Comment by XGBoost** [comment]
@zhaozj19 
Ubuntu16.04

**Comment by cathylacus** [comment]
> @zhaozj19
> Ubuntu16.04

I have the same erro，and my  package and environment :
Ubuntu 16.04.6  Cuda compilation tools, release 9.0, V9.0.176
cudnn 7.4.2    pytorch 1.0.1   GCC 5.4.0   progressbar2    3.50.1 
numpy   1.18.1    opencv-python   4.2.0.34    scikit-learn    0.22.2.post1
scipy           1.4.1     matplotlib      3.2.1      Pillow          7.0.0
So,I think I have installed the same version packages and environment as the author recommended. 
But,there is still error without dgcnn_ext.
thank for your watching, and looking forward to your reply!

**Comment by cathylacus** [comment]
> @XGBoost你使用linux或windows吗? 我用win10,无用的GCC。

请问您解决了么？

**Comment by XGBoost** [comment]
@cathylacus 
Just now, I tested my environment and it works.
![image](https://user-images.githubusercontent.com/23393128/80668940-bc4c3700-8ad5-11ea-9106-d89c10065106.png)
You have to ```import torch``` before using ```from pointmvsnet.functions import dgcnn_ext```.
And my environment is cuda9, cudnn6.0.21, pytorch1.0.1.
Details can be seen as follows.
```
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cycler==0.10.0
idna==2.9
imageio==2.8.0
joblib==0.14.1
jsonpatch==1.25
jsonpointer==2.0
kiwisolver==1.1.0
matplotlib==3.1.3
mkl-fft==1.0.6
mkl-random==1.0.1
mpld3==0.3.1.dev1
numpy==1.15.4
olefile==0.46
opencv-python==4.2.0.32
Pillow==6.1.0
progressbar2==3.47.0
protobuf==3.11.3
pycparser==2.19
pyparsing==2.4.6
python-dateutil==2.8.1
python-utils==2.3.0
PyYAML==5.3
pyzmq==19.0.0
rawpy==0.14.0
requests==2.23.0
scikit-learn==0.22.1
scipy==1.1.0
six==1.14.0
tensorboardX==2.0
torch==1.0.1.post2
torchfile==0.1.0
torchvision==0.2.2
tornado==6.0.4
tqdm==4.43.0
urllib3==1.25.8
visdom==0.1.8.9
websocket-client==0.57.0
yacs==0.1.6
```
What I want to say is that, make sure your cuda version and cudnn version is right (I am not sure other versions of cudnn is still works for this project, for example my cudnn version is not exactly as the recommended by the author).

**Comment by cathylacus** [comment]
> @cathylacus
> Just now, I tested my environment and it works.
> ![image](https://user-images.githubusercontent.com/23393128/80668940-bc4c3700-8ad5-11ea-9106-d89c10065106.png)
> You have to `import torch` before using `from pointmvsnet.functions import dgcnn_ext`.
> And my environment is cuda9, cudnn6.0.21, pytorch1.0.1.
> Details can be seen as follows.
> 
> ```
> certifi==2019.11.28
> cffi==1.14.0
> chardet==3.0.4
> cycler==0.10.0
> idna==2.9
> imageio==2.8.0
> joblib==0.14.1
> jsonpatch==1.25
> jsonpointer==2.0
> kiwisolver==1.1.0
> matplotlib==3.1.3
> mkl-fft==1.0.6
> mkl-random==1.0.1
> mpld3==0.3.1.dev1
> numpy==1.15.4
> olefile==0.46
> opencv-python==4.2.0.32
> Pillow==6.1.0
> progressbar2==3.47.0
> protobuf==3.11.3
> pycparser==2.19
> pyparsing==2.4.6
> python-dateutil==2.8.1
> python-utils==2.3.0
> PyYAML==5.3
> pyzmq==19.0.0
> rawpy==0.14.0
> requests==2.23.0
> scikit-learn==0.22.1
> scipy==1.1.0
> six==1.14.0
> tensorboardX==2.0
> torch==1.0.1.post2
> torchfile==0.1.0
> torchvision==0.2.2
> tornado==6.0.4
> tqdm==4.43.0
> urllib3==1.25.8
> visdom==0.1.8.9
> websocket-client==0.57.0
> yacs==0.1.6
> ```
> 
> What I want to say is that, make sure your cuda version and cudnn version is right (I am not sure other versions of cudnn is still works for this project, for example my cudnn version is not exactly as the recommended by the author).

Thanks！

**Comment by geviolet** [comment]
请问您是怎么解决的呢，我更换了和您一样的cudnn版本但是还是报错
