### ISSUE TITLE
How to render the point cloud as the paper show?

### ISSUE THREAD

**Issue by hetolin** [callmeray/PointMVSNet#19]
hi, I am reading your code recently. It looks great and useful. What's more, the picture in your paper impresses me a lot. Could I ask how you render the point clouds? use Maya or 3dsmax? Thanks a lot if you could share some details about how to render the point cloud~

**Comment by callmeray** [comment]
I used [CloudCompare](http://www.cloudcompare.org/) to render the point cloud.

**Comment by hetolin** [comment]
Thank you very much for your reply. I will have a try

**Comment by hetolin** [comment]
Sorry, Maybe I didn't express my question clearly. I mean that `figure 1` in your paper which are the point clouds of a buddha. Could I ask how you render the point clouds to get the pretty figure?

**Comment by callmeray** [comment]
Songfang rendered that image. I think she used Blender.

**Comment by hetolin** [comment]
OK, thanks a lot! I get it

**Comment by hansongfang** [comment]
For figure1 in the paper, I use the blender. In more detail, I generate a particle system from the mesh and the particle instance is presented by a sphere. This video can be helpful https://www.youtube.com/watch?v=BISscVV4L34.

**Comment by hetolin** [comment]
Thank you so much! Your description and the link is helpful. I will give it a go
