### ISSUE TITLE
data set mean and std calculation

### ISSUE THREAD

**Issue by eddienewton** [callmeray/PointMVSNet#3]
Hi,

Thanks for the great software.  I'm looking to test on my own dataset.

I had a question regarding the dataset mean and std calculation.  How did you go about approximating those?  They appear to be hard-coded values.

Are they calculated from a sparse pointcloud?

Thanks in advance!

**Comment by callmeray** [comment]
@eddienewton They are approximated from the coarse point clouds from our first stage.

**Comment by eddienewton** [comment]
Great!  Thanks for the quick reply and clarification.
