### ISSUE TITLE
Image resizing to reduce GPU RAM

### ISSUE THREAD

**Issue by KevinCain** [callmeray/PointMVSNet#4]
When testing, the default image dimensions are as follows:
    IMG_HEIGHT: 960
    IMG_WIDTH: 1280

Where would we edit these values in order to reduce the resolution?  I ask as my GPU has only 6GB RAM, where I believe you were testing with 11GB (e.g.,  1080Ti).

**Comment by callmeray** [comment]
@KevinCain You can edit these values in the configuration file `configs/dtu_wde3.yaml`
